name: Build

on:
  push:
    branches:
      - main

jobs:
  tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the repository
      - uses: actions/checkout@v4

      # 2. Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential libgtest-dev

      # 3. Create build directory and configure the project
      - name: Configure project
        run: |
          mkdir -p build
          cd build
          cmake ..

      # 4. Build the project
      - name: Build project
        run: |
          cd build
          cmake --build .

      # 5. Run tests
      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure